#
# Copyright 2015 Stephen Street <stephen@redrocketcomputing.com>
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/. 
#

LDFLAGS += -O3 
CFLAGS += -O3 
CPPFLAGS += -DNDEBUG -DBUILD_TYPE_RELEASE
